#!/bin/bash

OS="$(uname -s)"

if [ "$OS" != "Darwin" ] ; then
  echo "This script is only for Macintosh systems."
  exit 1
fi

brew update
brew doctor
brew upgrade

# I think this is pre-installed
# brew install mysql
# TODO: Should we also configure software, e.g. mysql, per:
# http://blog.joefallon.net/2013/10/install-mysql-on-mac-osx-using-homebrew/

# https://github.com/Homebrew/homebrew-php
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php55-xdebug

brew install tree

brew install nodejs
