#!/bin/bash

OS="$(uname -s)"

if [ "$(whoami)" == "root" ]
then
  echo "Do not run brew as root."
  exit 1
fi

if [ "$OS" != "Darwin" ] ; then
  echo "This script is only for Macintosh systems."
  exit 1
fi

if [ -z "$(which brew)" ]
then
  echo "You must install brew before running this script.  Visit http://brew.sh/ and see http://blog.strug.de/2012/06/my-homebrew-multi-user-setup/"
  exit 1
fi


#
# Get brew set up.
#
brew update
brew doctor
brew upgrade


#
# Tap some things
#
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php

#
# Useful CLI tools
#
brew install tree
brew install hub
brew install wget


# I think this is pre-installed
# brew install mysql
# TODO: Should we also configure software, e.g. mysql, per:
# http://blog.joefallon.net/2013/10/install-mysql-on-mac-osx-using-homebrew/

# https://github.com/Homebrew/homebrew-php

brew install php55-xdebug


#
# Some front-end tools
#
brew install nodejs

brew install chruby ruby-install
ruby-install ruby 2.0

