#!/bin/sh
# Reqs: curl, git
#
# GITHUBTOKEN: Create a personal access token here: https://github.com/settings/tokens
#
# Usage:
#
#   cd ~/work-dir
#   GITHUBTOKEN=... ORG=pantheon-cookbooks clone-all [filter]
#

if [ -z "$GITHUBTOKEN" ]; then
  echo "no GITHUBTOKEN= environment var specified"
  exit 1
fi

if [ -z "$ORG" ]; then
  echo "no ORG= environment var specified"
  exit 1
fi

FILTER=${1-.}

echo "FILTER is $FILTER"

echo "==> Cloning all repos from '$ORG'"

next="https://api.github.com/orgs/$ORG/repos?per_page=100"
while [ -n "$next" ] ; do
  #echo "Next is: $next"
  r=$(curl -u "$GITHUBTOKEN:x-oauth-basic" -s $next | grep --color=never '"ssh_url":' | sed -e 's/[^:]*: "//' -e 's/",*$//' | grep --color=never -i "$FILTER")
  repos="$repos
$r"
  next="$(curl -u "$GITHUBTOKEN:x-oauth-basic" -I -s "$next" | grep --color=never '^Link:' | grep --color=never 'rel="next"' | sed -e 's#.*\(http[^>]*\)>; rel="next".*#\1#')"
done

#cat <<< $repos
#exit 0

for repo in $repos
do
  dir=$(basename $repo .git)
  if [ -d "$dir" ]
  then
    echo "==> Updating $dir"
    (
      cd "$dir"
      git pull
    )
  else
    echo "==> Cloning $dir"
    git clone $repo $dir
  fi
done

# The ruby way
# | ruby -rubygems -e 'require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["ssh_url"]} ]}'

echo "==> Done."
