#!/bin/bash
#
# Usage:
#
# email-backup user1 user2
#
# Back up all the things
#

ARCHIVE_DIR=/data/archive/email
SERVER=ga@hydrogen.greenknowe.org

# %H     hour (00..23)
# day of week (0..6); 0 is Sunday
# %s     seconds since 1970-01-01 00:00:00 UTC
# %m     month (01..12)
HOUR=$(date +%H)
SEQUENCE=$(($(date +%m)%3))
EPOCH=$(date +%s)

#
# Parse command line args
#
while [ $# -gt 0 ] ; do

  option=$1
  shift

  case "$option" in
    --archive-dir )
      ARCHIVE_DIR="$1"
      shift
      ;;

    --server )
      SERVER="$1"
      shift
      ;;

    --* )
      echo "Unknown option $option"
      exit 1;
      ;;

    * )
      USERLIST="$USERLIST $option"
      ;;

  esac
done

#
# Backup email for each user in the user list in turn
#
for user in $USERLIST ; do
  # Once per day, do a rolling backup, keeping the last 7 days.
  # If the "ROLLING" folder exists, check to see if it is "too old".
  ROLLING=$ARCHIVE_DIR/$user/history/rolling/$SEQUENCE
  if [ -d "$ROLLING" ] ; then
    ROLLING_DIR_EPOCH=$(stat --format=%Y $ROLLING)
    DELTA=$(($EPOCH-$ROLLING_DIR_EPOCH))
    # Anything > 32 days is "too old".  If it is, delete it to
    # force a new rolling backup to be created.
    if [ "$DELTA" -gt "$((32*24*60*60))" ] ; then
      # TODO: Check to see if we should move the "ROLLING" folder
      # to a long-term-backup directory
      rm -rf "$ROLLING"
    fi
  fi
  # If there is no "ROLLING" folder, then create it with cp -alf,
  # which will create files with hard links rather than separate copies
  # of each file.
  if [ ! -d "$ROLLING" ] ; then
    mkdir -p $ROLLING
    cp -alf $ARCHIVE_DIR/$user/mail $ROLLING
  fi
  # Back up from server
  rsync -rlptz --exclude=backup $SERVER:/home/$user/mail $ARCHIVE_DIR/$user
  rsync -rlptz $SERVER:/var/mail/$user $ARCHIVE_DIR/$user/mail/var-mail-$user
done
